# Generated by Django 3.2.9 on 2022-01-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Description',
            new_name='description',
        ),
    ]
